#!/usr/bin/env python3
"""Regenerate the Material icon path table used by the library browser UI.

The Tkinter browser used to label its buttons with unicode/emoji glyphs
(▶ ⏸ ⚙ 🔀 …). Those render inconsistently across platforms -- emoji get
boxed frames on Windows and some code points fall back to tofu -- so the
UI now rasterizes Google Material Design icons instead (the same icon set
jellyfin-web uses, and the same one gen_osc_icons.py feeds to the MPV
OSC). See jellyfin_mpv_shim/library_browser/icons.py for the rasterizer.

This script downloads the SVG sources for the icons the UI needs and
writes their raw path ``d`` strings into

    jellyfin_mpv_shim/ui_icon_paths.py

which is committed so the running app never touches the network. Re-run it
only when the icon set changes.

Usage: ./gen_ui_icons.py [--svg-dir DIR]

By default the SVGs are fetched from marella/material-design-icons (a flat
mirror of Google's set, so no per-icon category is needed). Pass --svg-dir
to use a directory of pre-downloaded <name>.svg files instead.
"""

import os
import re
import sys
import urllib.request

# Material icon names the browser draws. Semantic UI roles map onto these
# in icons.py's ALIASES table; keep that map and this list in sync.
ICON_NAMES = [
    # transport / playback
    "play_arrow",
    "pause",
    "stop",
    "skip_previous",
    "skip_next",
    "fast_rewind",
    "fast_forward",
    "replay_10",
    "forward_30",
    "shuffle",
    "repeat",
    "repeat_one",
    "volume_up",
    # playback HUD (parity with the icons trickplay-jf-osc.lua embeds)
    "closed_caption",
    "audiotrack",
    "fullscreen",
    "fullscreen_exit",
    "bookmark",
    "hd",
    "undo",
    "redo",
    "close",
    # actions
    "favorite",
    "favorite_border",
    "playlist_add",
    "queue_music",
    "add",
    "home",
    "settings",
    "groups",
    "search",
    "file_download",
    "delete",
    "edit",
    "movie",
    "radio",
    # navigation / arrows
    "arrow_back",
    "chevron_left",
    "chevron_right",
    "vertical_align_top",
    "vertical_align_bottom",
    "keyboard_arrow_up",
    "keyboard_arrow_down",
    # tile badges / decoration
    "check",
    "music_note",
    "star",
    # user state
    "lock",
    "person",
    "person_add",
    # settings panels
    "refresh",
    "folder",
]

SVG_URL = (
    "https://raw.githubusercontent.com/marella/material-design-icons/"
    "main/svg/filled/{name}.svg"
)

TARGET = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "jellyfin_mpv_shim",
    "ui_icon_paths.py",
)


def get_svg(name, svg_dir):
    if svg_dir:
        with open(os.path.join(svg_dir, name + ".svg")) as f:
            return f.read()
    with urllib.request.urlopen(SVG_URL.format(name=name), timeout=30) as resp:
        return resp.read().decode("utf-8")


def extract_paths(svg):
    """Every filled path ``d`` attribute from an SVG document."""
    out = []
    for m in re.finditer(r"<path\b[^>]*>", svg):
        tag = m.group(0)
        if 'fill="none"' in tag:
            continue
        d = re.search(r'\bd="([^"]*)"', tag)
        if d:
            out.append(d.group(1).strip())
    return out


def main():
    svg_dir = None
    args = sys.argv[1:]
    if args and args[0] == "--svg-dir":
        svg_dir = args[1]

    entries = {}
    for name in ICON_NAMES:
        svg = get_svg(name, svg_dir)
        paths = extract_paths(svg)
        if not paths:
            raise SystemExit("no filled paths found for %s" % name)
        # Material icons are authored on a 24x24 viewBox; the rasterizer
        # assumes that. Multiple subpaths are joined -- the rasterizer fills
        # them together with the nonzero winding rule (so inner contours
        # become holes).
        entries[name] = " ".join(paths)

    lines = [
        '"""Material Design icon path data for the library browser UI.',
        "",
        "Generated by gen_ui_icons.py -- do not edit by hand.",
        "Path data from Google Material Design icons (Apache License 2.0):",
        "  https://github.com/google/material-design-icons",
        "Each value is one or more SVG path `d` strings on a 24x24 canvas,",
        "joined by spaces; icons.py rasterizes them with nonzero winding.",
        '"""',
        "",
        "ICON_PATHS = {",
    ]
    for name in ICON_NAMES:
        lines.append("    %r: %r," % (name, entries[name]))
    lines.append("}")
    block = "\n".join(lines) + "\n"

    with open(TARGET, "w") as f:
        f.write(block)
    print("wrote %s (%d icons)" % (TARGET, len(entries)))


if __name__ == "__main__":
    main()
