#!/usr/bin/env python3
"""Regenerate the vector icon table embedded in trickplay-jf-osc.lua.

The Jellyfin-styled OSC draws its buttons as ASS vector drawings ({\\p1}
paths) instead of relying on an icon font, because mpv only loads custom
fonts from its own config directory (which the shim does not control for
external mpv). The paths are converted from Google's Material Design icons
(Apache License 2.0, https://github.com/google/material-design-icons) --
the same icon set jellyfin-web uses via its ligature font.

Usage: ./gen_osc_icons.py [--svg-dir DIR]

By default the SVG sources are downloaded from the material-design-icons
repository. Pass --svg-dir to use a directory of pre-downloaded
<name>.svg files instead. The output is written into
jellyfin_mpv_shim/trickplay-jf-osc.lua between the
"-- BEGIN generated icons" / "-- END generated icons" markers (or to
stdout if the file or markers are missing).

Each icon is emitted on a 24x24 unit canvas. Two zero-length line
contours at (0,0) and (24,24) are prepended so libass computes the same
bounding box for every icon, which keeps \\an-based alignment stable
regardless of how much of the canvas the glyph ink covers.
"""

import math
import os
import re
import sys
import urllib.request

# icon name -> category in the material-design-icons repo layout
ICONS = {
    "play_arrow": "av",
    "pause": "av",
    "fast_rewind": "av",
    "fast_forward": "av",
    "skip_previous": "av",
    "skip_next": "av",
    "closed_caption": "av",
    "volume_up": "av",
    "volume_down": "av",
    "volume_off": "av",
    "undo": "content",
    "redo": "content",
    "audiotrack": "image",
    "settings": "action",
    "fullscreen": "navigation",
    "fullscreen_exit": "navigation",
    "check": "navigation",
    "close": "navigation",
    "arrow_back": "navigation",
    "favorite": "action",
    "groups": "social",
}

SVG_URL = (
    "https://raw.githubusercontent.com/google/material-design-icons/"
    "master/src/{category}/{name}/materialicons/24px.svg"
)

TARGET = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "jellyfin_mpv_shim",
    "trickplay-jf-osc.lua",
)
BEGIN_MARK = "-- BEGIN generated icons"
END_MARK = "-- END generated icons"

# SVG path -> ASS conversion lives in the package so the runtime UI
# (mpvtk.vector) and this generator share one implementation.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jellyfin_mpv_shim.svgpath import svg_path_to_ass  # noqa: E402

def get_svg(name, svg_dir):
    if svg_dir:
        with open(os.path.join(svg_dir, name + ".svg")) as f:
            return f.read()
    url = SVG_URL.format(category=ICONS[name], name=name)
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def main():
    svg_dir = None
    args = sys.argv[1:]
    if args and args[0] == "--svg-dir":
        svg_dir = args[1]

    # zero-length contours pinning the bbox to the full 24x24 canvas
    anchor = "m 0 0 l 0 0 m 24 24 l 24 24"

    lines = []
    lines.append(BEGIN_MARK)
    lines.append("-- Generated by gen_osc_icons.py -- do not edit by hand.")
    lines.append("-- Path data derived from Google Material Design icons,")
    lines.append("-- Copyright Google LLC, Apache License 2.0:")
    lines.append("--   https://github.com/google/material-design-icons")
    lines.append("-- All icons are ASS drawing commands on a 24x24 canvas.")
    lines.append("local icons = {")
    for name in sorted(ICONS):
        svg = get_svg(name, svg_dir)
        paths = extract_paths(svg)
        if not paths:
            raise SystemExit("no filled paths found for %s" % name)
        ass = " ".join(svg_path_to_ass(d) for d in paths)
        lines.append('    %s = "%s %s",' % (name, anchor, ass))
    lines.append("}")
    lines.append(END_MARK)
    block = "\n".join(lines)

    try:
        with open(TARGET) as f:
            content = f.read()
        begin = content.index(BEGIN_MARK)
        end = content.index(END_MARK) + len(END_MARK)
    except (OSError, ValueError):
        print(block)
        return
    with open(TARGET, "w") as f:
        f.write(content[:begin] + block + content[end:])
    print("updated %s (%d icons)" % (TARGET, len(ICONS)))


if __name__ == "__main__":
    main()
