"""The catalog's content key: the Jellyfin ``ServerId`` a row belongs to.

Separate from ``server_uuid``, which names a saved *login*, and separate again
from ``server_id``, which is the dead on-disk path key that must stay dead
(docs/do-not-fix.md 1).
"""

# Run as a script, this is what puts the repo root on sys.path -- without
# it `jellyfin_mpv_shim` resolves to whatever is pip-installed. A no-op
# under `discover`; tests/test_module_paths.py is the guard.
if __name__ == "__main__":
    import os
    import sys

    sys.path.insert(0, os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))))

import json
import os
import shutil
import sqlite3
import tempfile
import unittest
from unittest import mock

from tests._catalog_fixtures import set_columns
from jellyfin_mpv_shim.sync.db import ANY_SERVER, STATUS_COMPLETE, SyncDB
from jellyfin_mpv_shim.sync.manager import SyncManager

SERVER = "97fd53974c4c4b7cbac55e437dcc094f"
OTHER = "8178115f38154c1ebc64afe778261fda"

#: The `downloads` table as it stood before the content key existed. Written
#: out rather than derived from `_SCHEMA` on purpose: a migration test whose
#: "before" state is generated by the code under test cannot fail.
_OLD_TABLE = """
CREATE TABLE downloads (
    item_id TEXT PRIMARY KEY,
    server_id TEXT,
    server_uuid TEXT,
    type TEXT,
    name TEXT,
    series_id TEXT,
    series_name TEXT,
    season_id TEXT,
    parent_index INTEGER,
    index_number INTEGER,
    media_source_id TEXT,
    file_path TEXT,
    ext TEXT,
    size_bytes INTEGER DEFAULT 0,
    downloaded_bytes INTEGER DEFAULT 0,
    status TEXT,
    runtime_ticks INTEGER,
    item_json TEXT,
    source_json TEXT,
    userdata_json TEXT,
    added_at INTEGER,
    origin TEXT,
    completed_at INTEGER,
    watched_at INTEGER,
    library_id TEXT
);
"""


def _legacy_catalog(path, rows):
    """A catalog with no `content_server_id`, holding `rows`."""
    conn = sqlite3.connect(path)
    conn.execute(_OLD_TABLE)
    for item_id, server_uuid, item_json in rows:
        conn.execute(
            "INSERT INTO downloads (item_id, server_uuid, status, item_json, "
            "origin) VALUES (?,?,?,?,?)",
            (item_id, server_uuid, "complete", item_json, "user"))
    conn.commit()
    conn.close()


def _column(path, item_id, column):
    conn = sqlite3.connect(path)
    try:
        row = conn.execute(
            "SELECT %s FROM downloads WHERE item_id=?" % column,
            (item_id,)).fetchone()
        return row[0] if row else None
    finally:
        conn.close()


def _columns(path):
    conn = sqlite3.connect(path)
    try:
        return {r[1] for r in conn.execute("PRAGMA table_info(downloads)")}
    finally:
        conn.close()


class ContentKeyMigrationTest(unittest.TestCase):
    """The column arrives on an existing catalog and is filled from the
    manifest each row already carries -- no network, no homing pass."""

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.path = os.path.join(self.dir, "catalog.db")
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)

    def test_migration_fills_the_content_key_from_the_manifest(self):
        _legacy_catalog(self.path, [
            ("film", "uuid-a", json.dumps({"Id": "film", "ServerId": SERVER})),
        ])
        self.assertNotIn("content_server_id", _columns(self.path))
        SyncDB(self.path).close()
        self.assertIn("content_server_id", _columns(self.path))
        self.assertEqual(SERVER, _column(self.path, "film",
                                         "content_server_id"))

    def test_each_row_is_filled_from_its_own_manifest(self):
        _legacy_catalog(self.path, [
            ("a", "uuid-a", json.dumps({"Id": "a", "ServerId": SERVER})),
            ("b", "uuid-b", json.dumps({"Id": "b", "ServerId": OTHER})),
        ])
        SyncDB(self.path).close()
        self.assertEqual(SERVER, _column(self.path, "a", "content_server_id"))
        self.assertEqual(OTHER, _column(self.path, "b", "content_server_id"))

    def test_a_manifest_naming_no_server_leaves_it_null(self):
        """Measured as not arising (every DTO carries ServerId), but the
        migration must degrade rather than invent one."""
        _legacy_catalog(self.path, [
            ("film", "uuid-a", json.dumps({"Id": "film"})),
        ])
        SyncDB(self.path).close()
        self.assertIsNone(_column(self.path, "film", "content_server_id"))

    def test_a_malformed_manifest_does_not_fail_the_open(self):
        """One unparseable row must not cost the whole catalog. Every read
        path already tolerates this per row (repository._item_from_row); a
        migration that raised instead would turn it into a failed startup."""
        _legacy_catalog(self.path, [
            ("bad", "uuid-a", "{not json"),
            ("good", "uuid-a", json.dumps({"Id": "good", "ServerId": SERVER})),
        ])
        db = SyncDB(self.path)
        self.addCleanup(db.close)
        self.assertTrue(db.healthy())
        self.assertIsNone(_column(self.path, "bad", "content_server_id"))
        self.assertEqual(SERVER, _column(self.path, "good",
                                         "content_server_id"))

    def test_a_null_item_json_does_not_fail_the_open(self):
        _legacy_catalog(self.path, [("empty", "uuid-a", None)])
        db = SyncDB(self.path)
        self.addCleanup(db.close)
        self.assertTrue(db.healthy())
        self.assertIsNone(_column(self.path, "empty", "content_server_id"))

    def test_the_backfill_repairs_a_column_added_but_left_empty(self):
        """ALTER TABLE autocommits, so a crash between the ALTER and the
        backfill leaves the column present and empty. Reopening must repair
        it rather than see the column and skip -- the same rule `origin`
        already relies on (sync/db.py, _migrate)."""
        _legacy_catalog(self.path, [
            ("film", "uuid-a", json.dumps({"Id": "film", "ServerId": SERVER})),
        ])
        conn = sqlite3.connect(self.path)
        conn.execute("ALTER TABLE downloads ADD COLUMN content_server_id TEXT")
        conn.commit()
        conn.close()
        SyncDB(self.path).close()
        self.assertEqual(SERVER, _column(self.path, "film",
                                         "content_server_id"))

    def test_the_backfill_does_not_overwrite_a_filled_value(self):
        """Advance from NULL only. A row homed by a later build must not be
        re-derived from a manifest frozen at download time."""
        _legacy_catalog(self.path, [
            ("film", "uuid-a", json.dumps({"Id": "film", "ServerId": SERVER})),
        ])
        conn = sqlite3.connect(self.path)
        conn.execute("ALTER TABLE downloads ADD COLUMN content_server_id TEXT")
        conn.execute("UPDATE downloads SET content_server_id=?", (OTHER,))
        conn.commit()
        conn.close()
        SyncDB(self.path).close()
        self.assertEqual(OTHER, _column(self.path, "film",
                                        "content_server_id"))

    def test_an_older_build_can_still_open_a_migrated_catalog(self):
        """The additive-only contract. An added nullable column cannot break
        an older reader, so the check is that the old SELECT still runs."""
        _legacy_catalog(self.path, [
            ("film", "uuid-a", json.dumps({"Id": "film", "ServerId": SERVER})),
        ])
        SyncDB(self.path).close()
        conn = sqlite3.connect(self.path)
        try:
            got = conn.execute("SELECT item_id, server_uuid, status "
                               "FROM downloads").fetchall()
        finally:
            conn.close()
        self.assertEqual([("film", "uuid-a", "complete")], got)


class TheDeadPathKeyIsGoneTest(unittest.TestCase):
    """`downloads.server_id` was the on-disk path key and had to stay NULL.

    Filling it moved every existing download's directory out from under the row
    that names it, and `_remove_files` then reported success while deleting
    nothing. Two builds' worth of guards kept it empty; 3.0.0 takes the column
    away instead (CX8), which is the version of that repair nothing can undo by
    writing to it. docs/do-not-fix.md 1.

    These replace a class that asserted it stayed NULL. The hazard is the same
    hazard; what changed is that the answer is now the schema.
    """

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.path = os.path.join(self.dir, "catalog.db")
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)

    def _migrated(self, server_id=None):
        """A pre-3.0.0 catalog, opened once. `server_id` seeds the dead column,
        which is what a build with the apiclient typo fixed would have put
        there -- so the drop has to survive a value, not only a NULL."""
        _legacy_catalog(self.path, [
            ("film", "uuid-a", json.dumps({"Id": "film", "ServerId": SERVER})),
        ])
        if server_id is not None:
            conn = sqlite3.connect(self.path)
            conn.execute("UPDATE downloads SET server_id = ?", (server_id,))
            conn.commit()
            conn.close()
        SyncDB(self.path).close()

    def test_the_migration_takes_the_column_off_an_existing_catalog(self):
        self._migrated()
        self.assertNotIn("server_id", _columns(self.path))

    def test_even_when_something_had_filled_it(self):
        """The reachable version: the column is unwritable *by this app*, and
        a catalog from a build where it was not would still have to migrate."""
        self._migrated(server_id="a-server-dir")
        self.assertNotIn("server_id", _columns(self.path))

    def test_the_content_key_survives_the_rebuild(self):
        """The two were never the same column, and the rebuild must not take
        the one that scopes rows with the one that never did anything."""
        self._migrated(server_id="a-server-dir")
        cols = _columns(self.path)
        self.assertIn("content_server_id", cols)
        self.assertEqual(SERVER, _column(self.path, "film",
                                         "content_server_id"))

    def test_the_row_itself_survives_the_rebuild(self):
        """The part that would be unrecoverable if the copy were wrong: this is
        a table rebuild over the user's whole download catalog."""
        self._migrated(server_id="a-server-dir")
        conn = sqlite3.connect(self.path)
        try:
            row = conn.execute(
                "SELECT item_id, server_uuid, status, item_json, origin "
                "FROM downloads").fetchall()
        finally:
            conn.close()
        self.assertEqual(
            row, [("film", "uuid-a", "complete",
                   json.dumps({"Id": "film", "ServerId": SERVER}), "user")])

    def test_the_indexes_come_back_on_the_new_table(self):
        """A rebuild that forgot them leaves the catalog working and slow, which
        nothing else here would notice. `CREATE INDEX IF NOT EXISTS` is the trap:
        the names follow the old table through the rename, so the create is a
        no-op and the drop then takes them."""
        self._migrated()
        conn = sqlite3.connect(self.path)
        try:
            names = {r[1] for r in
                     conn.execute("PRAGMA index_list(downloads)")}
        finally:
            conn.close()
        self.assertIn("idx_downloads_series", names)
        self.assertIn("idx_downloads_status", names)

    def test_a_second_open_is_a_no_op(self):
        self._migrated()
        SyncDB(self.path).close()
        self.assertNotIn("server_id", _columns(self.path))
        conn = sqlite3.connect(self.path)
        try:
            leftovers = conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name='downloads_old'").fetchone()
        finally:
            conn.close()
        self.assertIsNone(leftovers, "the rebuild left its scratch table")


class ContentKeyWritersTest(unittest.TestCase):
    """Both row writers set the content key, and neither touches the path key.

    The two are `_add_row`, whose item comes from the server, and
    `_adopt_orphan`, whose item comes from the on-disk manifest. Measured:
    every DTO from either source names its server, so neither writer has an
    excuse to leave it NULL.
    """

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)
        self.root = os.path.join(self.dir, "store")
        os.makedirs(self.root)
        self.db = SyncDB(os.path.join(self.dir, "catalog.db"))
        self.addCleanup(self.db.close)
        self.mgr = SyncManager()
        self.mgr.db = self.db
        self.mgr.root = self.root

    def test_a_fresh_catalog_has_the_content_key(self):
        """From _SCHEMA, not only from the migration -- a fresh install is
        the common case and must not depend on the repair path."""
        self.assertIn("content_server_id",
                      _columns(os.path.join(self.dir, "catalog.db")))

    def test_upsert_writes_the_content_key(self):
        self.db.upsert({"item_id": "film", "content_server_id": SERVER,
                        "status": STATUS_COMPLETE})
        self.assertEqual(SERVER, self.db.get("film")["content_server_id"])

    def test_add_row_takes_it_from_the_item(self):
        self.mgr._add_row("uuid-a",
                          {"Id": "film", "Type": "Movie", "Name": "Film",
                           "ServerId": SERVER})
        row = self.db.get("film")
        self.assertEqual(SERVER, row["content_server_id"])
        self.assertEqual("uuid-a", row["server_uuid"])

    def test_add_row_cannot_fill_the_dead_path_key(self):
        """`_item_dir` derives the on-disk layout from that column, so a
        value there moves the directory out from under the row. The repair
        is that `_add_row` no longer *takes* a path key, rather than a guard
        on the value -- an argument that does not exist cannot be passed the
        day the apiclient's own spelling changes (docs/do-not-fix.md 1)."""
        self.mgr._add_row("uuid-a",
                          {"Id": "film", "Type": "Movie", "ServerId": SERVER})
        self.assertNotIn("server_id", self.db.get("film").keys())
        # The signature itself, not an exception raised somewhere downstream:
        # this used to pass a path key as the second positional and rely on
        # `item["Id"]` failing on a string, which is a TypeError about the
        # wrong thing -- and it changed to an AttributeError the moment a
        # different line touched `item` first. `_add_row` takes no path key;
        # asking the signature is what that sentence actually means.
        import inspect
        self.assertNotIn(
            "server_id",
            inspect.signature(self.mgr._add_row).parameters,
            "_add_row grew back a path key, which _item_dir would then use "
            "to move every download's directory out from under its row")

    def test_a_dto_that_does_not_name_its_server_is_refused(self):
        """A new row with no content server is a legacy state made
        permanent: it answers every server that asks, and the migration
        that fills the column from a manifest can never reach it. Measured
        against the 12.0 QA server on 2026-09-18 -- every downloadable type
        names its server, and so does a DTO fetched with a restricted
        `Fields` list -- so this refusal is expected never to fire, which is
        why it must be loud rather than a silent `or None`."""
        wrote = self.mgr._add_row("uuid-a", {"Id": "nameless",
                                             "Type": "Movie"})
        self.assertFalse(wrote, "_add_row claimed to have written a row for "
                                "an item that names no server")
        self.assertIsNone(self.db.get("nameless"),
                          "a row with no content server was written anyway")

    def _orphan(self, item_id, item):
        item_dir = os.path.join(self.root, "server", item_id)
        os.makedirs(item_dir)
        with open(os.path.join(item_dir, "media.mkv"), "wb") as fh:
            fh.write(b"x" * 64)
        with open(os.path.join(item_dir, "item.json"), "w",
                  encoding="utf-8") as fh:
            json.dump(item, fh)
        return item_dir

    def test_adopt_orphan_takes_it_from_the_manifest(self):
        item_dir = self._orphan("film", {"Id": "film", "Type": "Movie",
                                         "Name": "Film", "ServerId": SERVER})
        self.assertTrue(
            self.mgr._adopt_orphan("film", item_dir, None))
        self.assertEqual(SERVER, self.db.get("film")["content_server_id"])

    def test_an_adopted_row_is_scoped_even_with_no_login_to_name(self):
        """The case the withdrawn v1 plan mistook for the general one: an
        adopted row can have a NULL `server_uuid` ("None is survivable") and
        still know its server. Under the login key it answers nothing; under
        the content key it answers correctly."""
        item_dir = self._orphan("film", {"Id": "film", "Type": "Movie",
                                         "ServerId": SERVER})
        self.assertTrue(
            self.mgr._adopt_orphan("film", item_dir, None))
        row = self.db.get("film")
        self.assertIsNone(row["server_uuid"])
        self.assertEqual(SERVER, row["content_server_id"])

    def test_adopt_orphan_has_no_path_key_to_fill(self):
        """It was the one writer with a legitimate reason to set the dead
        column -- it reported the directory it actually found -- and with one
        store directory there is nothing to report. `TheDeadPathKeyIsGoneTest`
        is the schema half; this is that nothing writes it back."""
        import inspect
        item_dir = self._orphan("film", {"Id": "film", "Type": "Movie",
                                         "ServerId": SERVER})
        self.mgr._adopt_orphan("film", item_dir, None)
        self.assertNotIn("server_id", self.db.get("film").keys())
        self.assertNotIn(
            "server_dir",
            inspect.signature(self.mgr._adopt_orphan).parameters,
            "adoption grew back a per-server directory")


class TwoLoginsOneServerTest(unittest.TestCase):
    """The regression this whole repair exists for.

    Two saved logins on one Jellyfin server, one downloaded film. Every
    content question must answer the same for both, because "do we hold this"
    is a property of the server and the media, not of which account asked.

    At `cac4d584` the second login got: `lib1` for the library, `False` for
    is_complete, an empty badge set, and a DownloadCollision on enqueue --
    three of the four wrong, and inconsistent with the fourth.
    """

    SERVER_UUIDS = ("login-a", "login-b")

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)
        self.db = SyncDB(os.path.join(self.dir, "catalog.db"))
        self.addCleanup(self.db.close)
        # Downloaded by login A. Login B is the same person's other account
        # on the same box, or a second household member -- either way the
        # file on disk is the same file.
        self.db.upsert({
            "item_id": "film", "content_server_id": SERVER,
            "server_uuid": "login-a", "type": "Movie", "name": "Film",
            "series_id": "show", "season_id": "s1",
            "status": STATUS_COMPLETE, "library_id": "lib1",
            "item_json": json.dumps({"Id": "film", "ServerId": SERVER}),
        })

    def test_is_complete_answers_for_both_logins(self):
        for uuid in self.SERVER_UUIDS:
            with self.subTest(login=uuid):
                self.assertTrue(
                    self.db.is_complete("film", server_id=SERVER),
                    "the film is on this machine whichever account asks")

    def test_the_badge_sets_answer_for_both_logins(self):
        self.assertIn("film", self.db.downloaded_item_ids(server_id=SERVER))
        self.assertIn("show", self.db.downloaded_series_ids(server_id=SERVER))
        self.assertIn("s1", self.db.downloaded_season_ids(server_id=SERVER))

    def test_the_library_lookup_answers_for_both_logins(self):
        self.assertEqual("lib1", self.db.library_id("film", server_id=SERVER))

    def test_the_owner_is_the_server_not_the_login(self):
        """`enqueue` refuses on this. Keyed on the login it refused login B
        for a film login B can perfectly well have."""
        self.assertEqual(SERVER, self.db.owner_of("film"))

    def test_a_genuinely_different_server_is_still_refused(self):
        """The negative control, and the reason scoping exists at all: item
        ids are path-derived with no server component, so a *different*
        install can hand out this same id for a different file
        (docs/jellyfin-api-notes.md 13b)."""
        self.assertFalse(self.db.is_complete("film", server_id=OTHER))
        self.assertNotIn("film", self.db.downloaded_item_ids(server_id=OTHER))
        self.assertNotIn("show",
                         self.db.downloaded_series_ids(server_id=OTHER))
        self.assertIsNone(self.db.library_id("film", server_id=OTHER))

    def test_any_server_still_answers(self):
        """The fully-offline floor: no server to scope by, and the catalog is
        the only source of items there is. It is `ANY_SERVER` rather than
        `None` because those were one spelling and are two questions."""
        self.assertTrue(self.db.is_complete("film", server_id=ANY_SERVER))
        self.assertIn("film",
                      self.db.downloaded_item_ids(server_id=ANY_SERVER))

    def test_a_login_that_resolves_to_nothing_gets_nothing(self):
        """The question the floor used to swallow. `content_id_for` answers
        `None` for a login the registry has no credential for, and that must
        not read as "every server" -- item ids collide, so the permissive
        answer hands out a different film with the same id."""
        self.assertFalse(self.db.is_complete("film", server_id=None))
        self.assertEqual(set(), self.db.downloaded_item_ids(server_id=None))
        self.assertEqual(set(), self.db.downloaded_series_ids(server_id=None))
        self.assertIsNone(self.db.library_id("film", server_id=None))

    def test_the_scope_cannot_be_passed_positionally(self):
        """A guard against silent misuse. The parameter used to be a saved
        login and is now a Jellyfin ServerId -- same arity, different
        meaning -- so a call site that was not revisited must fail loudly
        rather than scope on the wrong key."""
        with self.assertRaises(TypeError):
            self.db.is_complete("film", SERVER)
        with self.assertRaises(TypeError):
            self.db.downloaded_item_ids(SERVER)


class ServerIdForTest(unittest.TestCase):
    """The one translation the content key needs: saved login -> ServerId.

    The inverse of the deleted `server_uuids_for`, and single-valued rather
    than a set, because many logins map to one server but never the reverse.
    """

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        patcher = mock.patch(
            "jellyfin_mpv_shim.users.conffile.get",
            side_effect=lambda app, conf_file, create=False: os.path.join(
                self.tmp, conf_file))
        self.addCleanup(patcher.stop)
        patcher.start()
        from jellyfin_mpv_shim.users import UserManager
        self.um = UserManager()
        self.um.users = [{
            "id": "local-1", "name": "A", "credentials": [
                {"uuid": "login-a", "Id": SERVER, "UserId": "jf-a"},
                {"uuid": "login-b", "Id": SERVER, "UserId": "jf-b"},
            ]}, {
            "id": "local-2", "name": "B", "credentials": [
                {"uuid": "login-c", "Id": OTHER, "UserId": "jf-c"},
            ]}]

    def test_two_logins_on_one_server_give_one_answer(self):
        self.assertEqual(SERVER, self.um.server_id_for("login-a"))
        self.assertEqual(SERVER, self.um.server_id_for("login-b"))

    def test_it_spans_local_users(self):
        """The catalog is one store per machine, so the lookup cannot stop at
        the active profile -- a row downloaded by the other profile still has
        to be scopable."""
        self.assertEqual(OTHER, self.um.server_id_for("login-c"))

    def test_an_unknown_login_answers_none(self):
        """A removed server whose downloads were kept. None means "cannot
        tell", which the reads take as unscoped rather than as "no such
        server" -- refusing there would take the downloads away."""
        self.assertIsNone(self.um.server_id_for("gone"))
        self.assertIsNone(self.um.server_id_for(None))

    def test_the_offline_pseudo_server_is_not_a_login(self):
        """The browser's offline source names its server "offline". It is a
        UI identity and must never reach a catalog query as itself; resolving
        it to None is what turns it into "unscoped"."""
        self.assertIsNone(self.um.server_id_for("offline"))


class TwoLoginsThroughTheManagerTest(unittest.TestCase):
    """The original reproducer, driven the way the app drives it: through
    saved logins, not through content ids.

    Measured at `cac4d584`, asking as the second login on one server:
    library `lib1`, is_complete `False`, badges `set()`, enqueue
    `DownloadCollision`. Three of the four wrong, and the one that answered
    disagreed with the three that did not -- which is what made it a scoping
    contradiction rather than a missing feature.
    """

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)
        self.db = SyncDB(os.path.join(self.dir, "catalog.db"))
        self.addCleanup(self.db.close)
        self.mgr = SyncManager()
        self.mgr.db = self.db
        self.mgr.root = self.dir
        self.mgr._add_row("login-a", {
            "Id": "film", "Type": "Movie", "Name": "Film",
            "SeriesId": "show", "SeasonId": "s1", "ServerId": SERVER})
        self.db.update("film", status=STATUS_COMPLETE)
        set_columns(self.db, "film", library_id="lib1")

        from jellyfin_mpv_shim.users import userManager
        # Two logins, one server. The second is the account that used to be
        # told the machine held nothing.
        patcher = mock.patch.object(userManager, "users", [{
            "id": "local", "credentials": [
                {"uuid": "login-a", "Id": SERVER, "UserId": "jf-a"},
                {"uuid": "login-b", "Id": SERVER, "UserId": "jf-b"},
                {"uuid": "login-far", "Id": OTHER, "UserId": "jf-c"},
            ]}])
        self.addCleanup(patcher.stop)
        patcher.start()

    def test_all_four_questions_agree_for_the_second_login(self):
        for login in ("login-a", "login-b"):
            with self.subTest(login=login):
                self.assertTrue(self.mgr.is_complete("film", login))
                self.assertEqual(
                    {"film"}, self.mgr.downloaded_item_ids(login))
                self.assertEqual(
                    {"show"}, self.mgr.downloaded_series_ids(login))
                self.assertEqual(
                    {"s1"}, self.mgr.downloaded_season_ids(login))

    def test_the_owner_is_the_server_so_the_second_login_is_not_refused(self):
        """`enqueue` refuses when `owner_of` disagrees with the asking
        server. Keyed on the login it refused login B for a film login B's
        own server is holding."""
        self.assertEqual(SERVER, self.db.owner_of("film"))
        self.assertEqual(SERVER, self.mgr.content_id_for("login-b"))

    def test_a_login_on_a_different_server_is_still_refused(self):
        """The negative control. Two installs both mounting `/media` hand
        out the same id for different files, so this must NOT converge."""
        self.assertFalse(self.mgr.is_complete("film", "login-far"))
        self.assertEqual(set(), self.mgr.downloaded_item_ids("login-far"))
        self.assertNotEqual(self.db.owner_of("film"),
                            self.mgr.content_id_for("login-far"))

    def test_the_offline_pseudo_server_reads_as_unscoped(self):
        """The downloads screen browses as "offline", which is no login at
        all. It must see the library rather than an empty one."""
        self.assertTrue(self.mgr.is_complete("film", "offline"))
        self.assertEqual({"film"}, self.mgr.downloaded_item_ids("offline"))


class SentinelReachingAWriteTest(unittest.TestCase):
    """`ANY_SERVER` is truthy, so a guard written for two values lets it past.

    The sentinel exists to say "every server" out loud where a falsy value used
    to mean it. It was made truthy so that `if server_id:` kept reading as "a
    scope was asked for" -- but a predicate can equally have meant "I hold a
    real server identity", and no boolean value serves both. These are the two
    sites where that difference is observable; the class is named after the
    shared cause rather than after either, because the next one will be a third
    site of the same kind and not a new bug.
    """

    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)
        self.db = SyncDB(os.path.join(self.dir, "catalog.db"))
        self.addCleanup(self.db.close)
        # `list_playlists` only answers for a playlist holding a COMPLETE
        # item, so a membership is part of the fixture rather than of what
        # is under test. Without it the assertions pass over an empty list
        # and the write could have failed unnoticed.
        self.db.upsert({"item_id": "film", "content_server_id": SERVER,
                        "status": STATUS_COMPLETE})
        # `server_id=None` to match the row the tests below write: this class
        # is about the *unscoped* ask, and NULL is its representable form.
        self.db.replace_playlist_items("pl", [("film", 0, 1)], server_id=None)

    def test_a_playlist_asked_for_unscoped_is_written_not_raised(self):
        """`server_id or None` passes the sentinel object itself to sqlite,
        which has no adapter for it and raises `ProgrammingError` -- so the
        whole playlist write is lost, not merely mis-scoped."""
        self.db.upsert_playlist("pl", ANY_SERVER, "uuid-a", "Example Playlist")
        row = self.db.list_playlists()
        self.assertEqual(1, len(row),
                         "the unscoped playlist write did not land at all")
        self.assertIsNone(
            row[0]["server_id"],
            "an unscoped ask must land as NULL -- the representable 'we could "
            "not tell', which `list_playlists` answers for")

    def test_no_column_of_an_unscoped_playlist_holds_the_sentinel(self):
        """The general form, so the value cannot reappear in a second column.

        The sentinel is passed only where a *scope* belongs. It is deliberately
        NOT passed as `server_uuid`: that parameter names a saved login, so a
        sentinel arriving there is a caller error, and normalising it would hide
        the bug instead of the value.
        """
        self.db.upsert_playlist("pl", ANY_SERVER, "uuid-a", "Example")
        for row in self.db.list_playlists():
            for key in row.keys():
                self.assertNotIsInstance(
                    row[key], type(ANY_SERVER),
                    "%s stored the sentinel object itself" % key)

    def test_a_client_that_will_not_resolve_claims_no_route(self):
        """`_connected_routes` keys by `content_id_for`'s answer, and the
        sentinel is truthy -- so a client whose login cannot be resolved was
        filed under "the server called ANY_SERVER" and then answered as *a*
        route. No longer inert: `routes_for` is looked up per download row,
        which is why `routes_for` refuses the sentinel on the way in as well.
        """
        mgr = SyncManager()

        class _Client:
            pass

        # `get_clients` is an instance attribute injected by `start`, not a
        # method -- patching the class raises AttributeError, which is a test
        # that cannot fail for its stated reason.
        mgr.get_clients = lambda: {"login-broken": _Client()}
        with mock.patch.object(SyncManager, "content_id_for",
                               staticmethod(lambda uuid: ANY_SERVER)):
            routes = mgr._connected_routes()
        self.assertEqual(
            {}, routes,
            "an unresolvable client was given a route under the sentinel; "
            "routes are keyed by a real ServerId or they are not routes")


if __name__ == "__main__":
    unittest.main()
