"""Material Design icons for the Tkinter library browser.

The browser used to label its controls with unicode/emoji glyphs (▶ ⏸ ⚙
🔀 …). Emoji render inconsistently across platforms -- Windows draws boxed
frames around them and some code points fall back to tofu -- which is why,
for example, the tile download badge had to be hand-drawn as a polygon.

This module rasterizes Google Material Design icons instead (the same set
jellyfin-web uses, and that gen_osc_icons.py feeds to the MPV OSC). The
SVG path data lives in the committed ``jellyfin_mpv_shim/ui_icon_paths.py`` (regenerated by
``gen_ui_icons.py``); here we parse each path, fill it with the nonzero
winding rule (so inner contours become holes -- the gear's centre, the CC
cutouts), and tint the resulting alpha mask to any theme colour on demand.

Everything is pure Python + Pillow. Pillow is already a hard dependency of
the browser (``thumbnails.py`` imports it at module load), so nothing new
is pulled in. The rendered ``PhotoImage`` objects are cached and held here
for the process lifetime -- the icon set is tiny -- so callers never need
to keep their own reference to stop Tk from garbage-collecting the image.
"""

import logging
import math
import tkinter
import weakref

from PIL import Image, ImageTk

from ..ui_icon_paths import ICON_PATHS

log = logging.getLogger("library_browser.icons")

# Semantic role -> Material icon name, so call sites can ask for the thing
# they mean. Names not listed here are looked up directly in ICON_PATHS.
ALIASES = {
    "back": "arrow_back",
    "play": "play_arrow",
    "download": "file_download",
    "favorite_off": "favorite_border",
    "add_to_queue": "add",
    "queue": "queue_music",
    "rename": "edit",
    "trailer": "movie",
    "instant_mix": "radio",
    "move_top": "vertical_align_top",
    "move_bottom": "vertical_align_bottom",
    "move_up": "keyboard_arrow_up",
    "move_down": "keyboard_arrow_down",
    "page_left": "chevron_left",
    "page_right": "chevron_right",
}

CANVAS = 24.0  # Material icons are authored on a 24x24 grid.
_SUPERSAMPLE = 4  # render at Nx then downscale for anti-aliasing.

_NUM_START = "+-.0123456789"
_CMDS = set("MmLlHhVvCcSsQqTtAaZz")

_mask_cache = {}   # (name, size) -> PIL "L" alpha mask (root-independent)

# A ``PhotoImage`` belongs to the Tk interpreter it was built under, so the
# cache is keyed per root: a WeakKeyDictionary drops a root's images when that
# root is garbage-collected (e.g. between tests that spin up many windows),
# which avoids handing a stale "pyimageN" from a destroyed interpreter to a new
# one. In normal use the browser is a single process with a single root.
_photo_caches = weakref.WeakKeyDictionary()  # root -> {(name,size,color): photo}

# The Tk root that icons bind to when a call doesn't name one. Set by the
# browser once its window exists. Needed because ``tkinter._default_root``
# stays pinned to the *first* Tk() ever created, which is the wrong
# interpreter for a second window built later in the same process (as the
# test harness does) -- a PhotoImage bound to a dead root raises
# "image pyimageN doesn't exist" when a live widget tries to use it.
_current_root = None


def set_root(root):
    """Register the Tk root that subsequent :func:`get_photo` calls bind to."""
    global _current_root
    _current_root = root


def _tokenize(d):
    toks = []
    i, n = 0, len(d)
    while i < n:
        ch = d[i]
        if ch in _CMDS:
            toks.append(ch)
            i += 1
        elif ch in _NUM_START:
            j = i + 1
            # a number: optional sign already consumed, digits, one dot,
            # optional exponent. SVG allows a sign only after 'e'/'E'.
            seen_dot = ch == "."
            seen_exp = False
            while j < n:
                c = d[j]
                if c.isdigit():
                    j += 1
                elif c == "." and not seen_dot and not seen_exp:
                    seen_dot = True
                    j += 1
                elif c in "eE" and not seen_exp:
                    seen_exp = True
                    j += 1
                    if j < n and d[j] in "+-":
                        j += 1
                else:
                    break
            toks.append(float(d[i:j]))
            i = j
        else:
            i += 1  # whitespace / comma
    return toks


def _arc_to_cubics(x0, y0, rx, ry, phi_deg, large, sweep, x, y):
    """SVG elliptical arc -> list of ("b", c1x, c1y, c2x, c2y, x, y) cubics
    (or ("l", x, y) for a degenerate arc). Endpoint-to-centre conversion per
    the SVG spec, one cubic per <= 90 degree slice. Ported from
    gen_osc_icons.py -- Material icons like ``search`` draw circles with arcs.
    """
    if rx == 0 or ry == 0:
        return [("l", x, y)]
    rx, ry = abs(rx), abs(ry)
    phi = math.radians(phi_deg % 360)
    cosp, sinp = math.cos(phi), math.sin(phi)

    dx2, dy2 = (x0 - x) / 2.0, (y0 - y) / 2.0
    x1p = cosp * dx2 + sinp * dy2
    y1p = -sinp * dx2 + cosp * dy2

    lam = (x1p / rx) ** 2 + (y1p / ry) ** 2
    if lam > 1:
        s = math.sqrt(lam)
        rx, ry = rx * s, ry * s

    num = rx**2 * ry**2 - rx**2 * y1p**2 - ry**2 * x1p**2
    den = rx**2 * y1p**2 + ry**2 * x1p**2
    co = math.sqrt(max(0.0, num / den)) if den else 0.0
    if large == sweep:
        co = -co
    cxp = co * rx * y1p / ry
    cyp = -co * ry * x1p / rx

    cx = cosp * cxp - sinp * cyp + (x0 + x) / 2.0
    cy = sinp * cxp + cosp * cyp + (y0 + y) / 2.0

    def angle(ux, uy, vx, vy):
        dot = ux * vx + uy * vy
        length = math.hypot(ux, uy) * math.hypot(vx, vy)
        ang = math.acos(max(-1.0, min(1.0, dot / length))) if length else 0.0
        if ux * vy - uy * vx < 0:
            ang = -ang
        return ang

    theta1 = angle(1, 0, (x1p - cxp) / rx, (y1p - cyp) / ry)
    dtheta = angle(
        (x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry
    )
    if not sweep and dtheta > 0:
        dtheta -= 2 * math.pi
    elif sweep and dtheta < 0:
        dtheta += 2 * math.pi

    nseg = max(1, int(math.ceil(abs(dtheta) / (math.pi / 2))))
    delta = dtheta / nseg
    k = 4.0 / 3.0 * math.tan(delta / 4.0)

    out = []
    t = theta1
    for _ in range(nseg):
        cos1, sin1 = math.cos(t), math.sin(t)
        cos2, sin2 = math.cos(t + delta), math.sin(t + delta)

        def pt(c, s):
            return (cx + rx * c * cosp - ry * s * sinp,
                    cy + rx * c * sinp + ry * s * cosp)

        def dpt(c, s):
            return (-rx * s * cosp - ry * c * sinp,
                    -rx * s * sinp + ry * c * cosp)

        p1 = pt(cos1, sin1)
        p2 = pt(cos2, sin2)
        d1 = dpt(cos1, sin1)
        d2 = dpt(cos2, sin2)
        out.append(("b", p1[0] + k * d1[0], p1[1] + k * d1[1],
                    p2[0] - k * d2[0], p2[1] - k * d2[1], p2[0], p2[1]))
        t += delta
    return out


def _flatten_cubic(p0, p1, p2, p3, out, steps=16):
    for k in range(1, steps + 1):
        t = k / steps
        mt = 1 - t
        a, b, c, e = mt * mt * mt, 3 * mt * mt * t, 3 * mt * t * t, t * t * t
        out.append(
            (
                a * p0[0] + b * p1[0] + c * p2[0] + e * p3[0],
                a * p0[1] + b * p1[1] + c * p2[1] + e * p3[1],
            )
        )


def _parse_path(d):
    """SVG path ``d`` -> list of contours, each a list of (x, y) points.

    Handles the command subset Material icons use (M L H V C S Q T Z, in
    both absolute and relative forms). Beziers are flattened to polylines;
    the caller fills the contours with the nonzero winding rule.
    """
    toks = _tokenize(d)
    i, ntok = 0, len(toks)
    cmd = None
    cx = cy = sx = sy = 0.0
    pcx = pcy = None  # last cubic control point, for S/s smoothing
    contours = []
    cur = None

    def take(k):
        nonlocal i
        vals = toks[i : i + k]
        i += k
        return vals

    while i < ntok:
        if isinstance(toks[i], str):
            cmd = toks[i]
            i += 1
            if cmd in "Zz":
                if cur:
                    cur.append((sx, sy))
                cx, cy = sx, sy
                pcx = pcy = None
                continue
        elif cmd in "Mm":
            # implicit lineto for extra coordinate pairs after a moveto
            cmd = "L" if cmd == "M" else "l"

        rel = cmd.islower()
        c = cmd.upper()
        new_pc = None

        if c == "M":
            x, y = take(2)
            if rel:
                x, y = cx + x, cy + y
            cur = [(x, y)]
            contours.append(cur)
            cx, cy, sx, sy = x, y, x, y
        elif c == "L":
            x, y = take(2)
            if rel:
                x, y = cx + x, cy + y
            cur.append((x, y))
            cx, cy = x, y
        elif c == "H":
            (x,) = take(1)
            if rel:
                x = cx + x
            cur.append((x, cy))
            cx = x
        elif c == "V":
            (y,) = take(1)
            if rel:
                y = cy + y
            cur.append((cx, y))
            cy = y
        elif c in "CS":
            if c == "C":
                x1, y1, x2, y2, x, y = take(6)
                if rel:
                    x1, y1, x2, y2, x, y = (
                        cx + x1, cy + y1, cx + x2, cy + y2, cx + x, cy + y,
                    )
            else:
                x2, y2, x, y = take(4)
                if rel:
                    x2, y2, x, y = cx + x2, cy + y2, cx + x, cy + y
                if pcx is not None:
                    x1, y1 = 2 * cx - pcx, 2 * cy - pcy
                else:
                    x1, y1 = cx, cy
            _flatten_cubic((cx, cy), (x1, y1), (x2, y2), (x, y), cur)
            new_pc = (x2, y2)
            cx, cy = x, y
        elif c in "QT":
            if c == "Q":
                qx, qy, x, y = take(4)
                if rel:
                    qx, qy, x, y = cx + qx, cy + qy, cx + x, cy + y
            else:
                x, y = take(2)
                if rel:
                    x, y = cx + x, cy + y
                qx, qy = cx, cy  # quadratic smoothing is rare in this set
            # quadratic -> cubic control points
            x1, y1 = cx + 2.0 / 3.0 * (qx - cx), cy + 2.0 / 3.0 * (qy - cy)
            x2, y2 = x + 2.0 / 3.0 * (qx - x), y + 2.0 / 3.0 * (qy - y)
            _flatten_cubic((cx, cy), (x1, y1), (x2, y2), (x, y), cur)
            cx, cy = x, y
        elif c == "A":
            rx, ry, rot, large, sweep, x, y = take(7)
            if rel:
                x, y = cx + x, cy + y
            for seg in _arc_to_cubics(cx, cy, rx, ry, rot,
                                      bool(large), bool(sweep), x, y):
                if seg[0] == "l":
                    cur.append((seg[1], seg[2]))
                else:
                    _flatten_cubic((cx, cy), (seg[1], seg[2]),
                                   (seg[3], seg[4]), (seg[5], seg[6]), cur)
                    cx, cy = seg[5], seg[6]
            cx, cy = x, y
        else:
            take(1)  # unknown command; consume one token defensively

        pcx, pcy = new_pc if new_pc else (None, None)

    return contours


def _rasterize(contours, size):
    """Nonzero-winding scanline fill -> Pillow ``L`` alpha mask (size x size)."""
    ss = _SUPERSAMPLE
    hi = size * ss
    scale = hi / CANVAS
    edges = []  # ( y0, y1, x_at_y0, dx/dy, winding)
    for cont in contours:
        pts = [(x * scale, y * scale) for x, y in cont]
        m = len(pts)
        for j in range(m):
            x0, y0 = pts[j]
            x1, y1 = pts[(j + 1) % m]
            if y0 == y1:
                continue
            w = 1 if y1 > y0 else -1
            if y0 > y1:
                x0, y0, x1, y1 = x1, y1, x0, y0
            edges.append((y0, y1, x0, (x1 - x0) / (y1 - y0), w))

    buf = bytearray(hi * hi)
    for yi in range(hi):
        yc = yi + 0.5
        xs = [
            (x0 + (yc - y0) * dxdy, w)
            for (y0, y1, x0, dxdy, w) in edges
            if y0 <= yc < y1
        ]
        if not xs:
            continue
        xs.sort()
        wind = 0
        row = yi * hi
        for k in range(len(xs) - 1):
            wind += xs[k][1]
            if wind != 0:
                xa = max(0, int(math.ceil(xs[k][0] - 0.5)))
                xb = min(hi, int(math.ceil(xs[k + 1][0] - 0.5)))
                for x in range(xa, xb):
                    buf[row + x] = 255

    mask = Image.frombytes("L", (hi, hi), bytes(buf))
    if ss != 1:
        mask = mask.resize((size, size), Image.LANCZOS)
    return mask


def _resolve(name):
    material = ALIASES.get(name, name)
    if material not in ICON_PATHS:
        raise KeyError("unknown icon %r" % name)
    return material


def get_mask(name, size):
    """Cached grayscale alpha mask for an icon at a pixel size."""
    material = _resolve(name)
    key = (material, size)
    mask = _mask_cache.get(key)
    if mask is None:
        contours = _parse_path(ICON_PATHS[material])
        mask = _rasterize(contours, size)
        _mask_cache[key] = mask
    return mask


def _hex_to_rgb(color):
    c = color.lstrip("#")
    if len(c) == 3:
        c = "".join(ch * 2 for ch in c)
    return int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16)


def get_image(name, size=20, color="#e8e8e8"):
    """A tinted Pillow ``RGBA`` image of the icon. Rarely needed directly;
    prefer :func:`get_photo` for Tk widgets."""
    rgb = _hex_to_rgb(color)
    img = Image.new("RGBA", (size, size), rgb + (0,))
    img.putalpha(get_mask(name, size))
    return img


def get_photo(name, size=20, color="#e8e8e8", master=None):
    """Cached ``ImageTk.PhotoImage`` of an icon, tinted to ``color``.

    Must be called on the Tk UI thread (Tk images are thread-affine) after a
    root window exists. ``master`` is the Tk widget/root to bind the image to
    (defaults to the current default root). The image is cached per root and
    referenced for that root's lifetime, so callers need not keep it alive
    themselves (e.g. canvas items whose only reference is the cache).
    """
    material = _resolve(name)
    root = master or _current_root or tkinter._default_root
    cache = _photo_caches.get(root)
    if cache is None:
        cache = {}
        _photo_caches[root] = cache
    key = (material, size, color.lower())
    photo = cache.get(key)
    if photo is None:
        photo = ImageTk.PhotoImage(get_image(material, size, color), master=root)
        cache[key] = photo
    return photo
